"""initial schema

Revision ID: f37b766f11e4
Revises: 
Create Date: 2026-09-19 16:44:26.266553+00:00
"""

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision = 'f37b766f11e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('profile_photo_url', sa.String(length=500), nullable=True),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('connections',
    sa.Column('requester_id', sa.UUID(), nullable=False),
    sa.Column('receiver_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', 'blocked', name='connection_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('requester_id <> receiver_id', name=op.f('ck_connections_no_self_connection')),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], name=op.f('fk_connections_receiver_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], name=op.f('fk_connections_requester_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connections')),
    sa.UniqueConstraint('requester_id', 'receiver_id', name='uq_connections_pair')
    )
    op.create_index('ix_connections_receiver_id', 'connections', ['receiver_id'], unique=False)
    op.create_index('ix_connections_requester_id', 'connections', ['requester_id'], unique=False)
    op.create_index('ix_connections_status', 'connections', ['status'], unique=False)
    op.create_table('conversation_participants',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_conversation_participants_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_conversation_participants_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversation_id', 'user_id', name='pk_conversation_participants')
    )
    op.create_index('ix_conversation_participants_user_id', 'conversation_participants', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('fk_messages_sender_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index('ix_messages_conversation_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index('ix_messages_sender_id', 'messages', ['sender_id'], unique=False)
    op.create_table('ratings',
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('is_verified_student', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name=op.f('ck_ratings_rating_range')),
    sa.CheckConstraint('reviewer_id <> teacher_id', name=op.f('ck_ratings_no_self_rating')),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_ratings_reviewer_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name=op.f('fk_ratings_teacher_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ratings')),
    sa.UniqueConstraint('reviewer_id', 'teacher_id', name='uq_ratings_reviewer_teacher')
    )
    op.create_index('ix_ratings_reviewer_id', 'ratings', ['reviewer_id'], unique=False)
    op.create_index('ix_ratings_teacher_id', 'ratings', ['teacher_id'], unique=False)
    op.create_table('recommendation_events',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('recommended_user_id', sa.UUID(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('feedback', sa.Enum('none', 'saved', 'dismissed', 'connected', name='recommendation_feedback'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recommended_user_id'], ['users.id'], name=op.f('fk_recommendation_events_recommended_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recommendation_events_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendation_events')),
    sa.UniqueConstraint('user_id', 'recommended_user_id', name='uq_recommendation_pair')
    )
    op.create_index('ix_recommendation_events_user_id', 'recommendation_events', ['user_id'], unique=False)
    op.create_table('resources',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_url', sa.String(length=1000), nullable=True),
    sa.Column('file_name', sa.String(length=300), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('subject', sa.String(length=80), nullable=True),
    sa.Column('education_level', sa.String(length=50), nullable=True),
    sa.Column('difficulty', sa.String(length=30), nullable=True),
    sa.Column('teaching_method', sa.String(length=50), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), server_default=sa.text("'{}'::varchar[]"), nullable=False),
    sa.Column('download_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_resources_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resources'))
    )
    op.create_index('ix_resources_created_at', 'resources', ['created_at'], unique=False)
    op.create_index('ix_resources_difficulty', 'resources', ['difficulty'], unique=False)
    op.create_index('ix_resources_education_level', 'resources', ['education_level'], unique=False)
    op.create_index('ix_resources_embedding_hnsw', 'resources', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_resources_owner_id', 'resources', ['owner_id'], unique=False)
    op.create_index('ix_resources_subject', 'resources', ['subject'], unique=False)
    op.create_index('ix_resources_tags', 'resources', ['tags'], unique=False, postgresql_using='gin')
    op.create_index('ix_resources_teaching_method', 'resources', ['teaching_method'], unique=False)
    op.create_table('teacher_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('location_name', sa.String(length=200), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('education_levels', postgresql.ARRAY(sa.String()), server_default=sa.text("'{}'::varchar[]"), nullable=False),
    sa.Column('subjects', postgresql.ARRAY(sa.String()), server_default=sa.text("'{}'::varchar[]"), nullable=False),
    sa.Column('fields_of_expertise', postgresql.ARRAY(sa.String()), server_default=sa.text("'{}'::varchar[]"), nullable=False),
    sa.Column('teaching_levels', postgresql.ARRAY(sa.String()), server_default=sa.text("'{}'::varchar[]"), nullable=False),
    sa.Column('teaching_methods', postgresql.ARRAY(sa.String()), server_default=sa.text("'{}'::varchar[]"), nullable=False),
    sa.Column('teaching_style', sa.Text(), nullable=True),
    sa.Column('class_size', sa.Integer(), nullable=True),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.Column('languages', postgresql.ARRAY(sa.String()), server_default=sa.text("'{}'::varchar[]"), nullable=False),
    sa.Column('institution', sa.String(length=200), nullable=True),
    sa.Column('institution_type', sa.String(length=50), nullable=True),
    sa.Column('average_rating', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('rating_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('teaching_style_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('class_size IS NULL OR class_size > 0', name=op.f('ck_teacher_profiles_class_size_positive')),
    sa.CheckConstraint('latitude IS NULL OR (latitude >= -90 AND latitude <= 90)', name=op.f('ck_teacher_profiles_latitude_range')),
    sa.CheckConstraint('longitude IS NULL OR (longitude >= -180 AND longitude <= 180)', name=op.f('ck_teacher_profiles_longitude_range')),
    sa.CheckConstraint('years_experience IS NULL OR years_experience >= 0', name=op.f('ck_teacher_profiles_experience_non_negative')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_teacher_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teacher_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_teacher_profiles_user_id'))
    )
    op.create_index('ix_teacher_profiles_average_rating', 'teacher_profiles', ['average_rating'], unique=False)
    op.create_index('ix_teacher_profiles_class_size', 'teacher_profiles', ['class_size'], unique=False)
    op.create_index('ix_teacher_profiles_education_levels', 'teacher_profiles', ['education_levels'], unique=False, postgresql_using='gin')
    op.create_index('ix_teacher_profiles_embedding_hnsw', 'teacher_profiles', ['teaching_style_embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'teaching_style_embedding': 'vector_cosine_ops'})
    op.create_index('ix_teacher_profiles_expertise', 'teacher_profiles', ['fields_of_expertise'], unique=False, postgresql_using='gin')
    op.create_index('ix_teacher_profiles_location', 'teacher_profiles', ['latitude', 'longitude'], unique=False)
    op.create_index('ix_teacher_profiles_subjects', 'teacher_profiles', ['subjects'], unique=False, postgresql_using='gin')
    op.create_index('ix_teacher_profiles_teaching_levels', 'teacher_profiles', ['teaching_levels'], unique=False, postgresql_using='gin')
    op.create_index('ix_teacher_profiles_teaching_methods', 'teacher_profiles', ['teaching_methods'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_teacher_profiles_teaching_methods', table_name='teacher_profiles', postgresql_using='gin')
    op.drop_index('ix_teacher_profiles_teaching_levels', table_name='teacher_profiles', postgresql_using='gin')
    op.drop_index('ix_teacher_profiles_subjects', table_name='teacher_profiles', postgresql_using='gin')
    op.drop_index('ix_teacher_profiles_location', table_name='teacher_profiles')
    op.drop_index('ix_teacher_profiles_expertise', table_name='teacher_profiles', postgresql_using='gin')
    op.drop_index('ix_teacher_profiles_embedding_hnsw', table_name='teacher_profiles', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'teaching_style_embedding': 'vector_cosine_ops'})
    op.drop_index('ix_teacher_profiles_education_levels', table_name='teacher_profiles', postgresql_using='gin')
    op.drop_index('ix_teacher_profiles_class_size', table_name='teacher_profiles')
    op.drop_index('ix_teacher_profiles_average_rating', table_name='teacher_profiles')
    op.drop_table('teacher_profiles')
    op.drop_index('ix_resources_teaching_method', table_name='resources')
    op.drop_index('ix_resources_tags', table_name='resources', postgresql_using='gin')
    op.drop_index('ix_resources_subject', table_name='resources')
    op.drop_index('ix_resources_owner_id', table_name='resources')
    op.drop_index('ix_resources_embedding_hnsw', table_name='resources', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('ix_resources_education_level', table_name='resources')
    op.drop_index('ix_resources_difficulty', table_name='resources')
    op.drop_index('ix_resources_created_at', table_name='resources')
    op.drop_table('resources')
    op.drop_index('ix_recommendation_events_user_id', table_name='recommendation_events')
    op.drop_table('recommendation_events')
    op.drop_index('ix_ratings_teacher_id', table_name='ratings')
    op.drop_index('ix_ratings_reviewer_id', table_name='ratings')
    op.drop_table('ratings')
    op.drop_index('ix_messages_sender_id', table_name='messages')
    op.drop_index('ix_messages_conversation_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_conversation_participants_user_id', table_name='conversation_participants')
    op.drop_table('conversation_participants')
    op.drop_index('ix_connections_status', table_name='connections')
    op.drop_index('ix_connections_requester_id', table_name='connections')
    op.drop_index('ix_connections_receiver_id', table_name='connections')
    op.drop_table('connections')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('conversations')
    # ### end Alembic commands ###
    # Enum types outlive their tables unless they are dropped explicitly.
    sa.Enum(name='recommendation_feedback').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='connection_status').drop(op.get_bind(), checkfirst=True)
